name: imtixon_4_oy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  adaptive_theme: ^3.6.0
  cloud_firestore: ^5.1.0
  easy_localization: ^3.0.7
  firebase_auth: ^5.1.2
  firebase_cloud_firestore: ^5.0.1
  firebase_core: ^3.2.0
  firebase_messaging: ^15.0.3
  firebase_storage: ^12.1.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.1+2
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  flutter_timezone: ^2.0.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  localization: ^2.1.1
  location: ^7.0.0
  mark: ^0.3.0
  provider: ^6.1.2
  timezone: ^0.9.4
  yandex_mapkit: ^4.1.0
  zoom_tap_animation: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - resources/langs/